-- ============================================================
-- TIS PORTAL — STORAGE SECURITY HARDENING
-- Buckets:
--   newsletters      (public PDFs)
--   payment-proofs   (private parent payment evidence)
--
-- Manual Supabase execution required.
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- 1. BUCKET CONFIGURATION
-- ------------------------------------------------------------

-- Newsletters are intentionally public because the application stores a
-- public URL and opens it directly for Teacher/Student/Parent users.
-- Restrict uploads to PDFs and cap at 10 MB.
UPDATE storage.buckets
SET
  public = true,
  file_size_limit = 10485760,
  allowed_mime_types = ARRAY['application/pdf']::text[]
WHERE id = 'newsletters';

-- Payment proofs must remain private. Preserve the existing 10 MB limit and
-- allowed JPG/JPEG/PNG/PDF types explicitly.
UPDATE storage.buckets
SET
  public = false,
  file_size_limit = 10485760,
  allowed_mime_types = ARRAY[
    'image/jpeg',
    'image/jpg',
    'image/png',
    'application/pdf'
  ]::text[]
WHERE id = 'payment-proofs';

-- ------------------------------------------------------------
-- 2. REMOVE THE DANGEROUS GLOBAL STORAGE POLICIES
-- ------------------------------------------------------------
-- These old policies used WITH CHECK (true) / USING (true), which meant the
-- anon role was not restricted to a particular bucket.

DROP POLICY IF EXISTS "Allow Uploads w1pnpy_0" ON storage.objects;
DROP POLICY IF EXISTS "Allow Uploads w1pnpy_1" ON storage.objects;

-- Remove the old broad newsletter policies before recreating trusted-admin
-- versions.
DROP POLICY IF EXISTS "Allow authenticated delete" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated select" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated uploads" ON storage.objects;

-- Remove our replacement policies if this migration is re-run.
DROP POLICY IF EXISTS payment_proofs_anon_insert ON storage.objects;
DROP POLICY IF EXISTS payment_proofs_anon_select ON storage.objects;
DROP POLICY IF EXISTS payment_proofs_anon_delete_own_folder ON storage.objects;

DROP POLICY IF EXISTS newsletters_admin_insert ON storage.objects;
DROP POLICY IF EXISTS newsletters_admin_select ON storage.objects;
DROP POLICY IF EXISTS newsletters_admin_delete ON storage.objects;
DROP POLICY IF EXISTS newsletters_admin_update ON storage.objects;

-- ------------------------------------------------------------
-- 3. PAYMENT PROOFS
-- ------------------------------------------------------------
-- Custom Parent/Accountant sessions use the Supabase anon key.
-- The current frontend uploads parent proofs directly from the browser and
-- Accountants create signed URLs from the private bucket, so anon requires
-- narrowly-scoped access to THIS bucket only.
--
-- This closes the previous cross-bucket exposure without changing the working
-- custom-auth architecture.

CREATE POLICY payment_proofs_anon_insert
ON storage.objects
FOR INSERT
TO anon
WITH CHECK (
  bucket_id = 'payment-proofs'
  AND name IS NOT NULL
  AND name <> ''
);

CREATE POLICY payment_proofs_anon_select
ON storage.objects
FOR SELECT
TO anon
USING (
  bucket_id = 'payment-proofs'
);

-- Parent upload cleanup currently calls .remove() if the payment-submission
-- RPC fails. Allow anon deletes only in payment-proofs. Filenames are random
-- UUID-based paths generated by the client; no other bucket can be touched.
CREATE POLICY payment_proofs_anon_delete_own_folder
ON storage.objects
FOR DELETE
TO anon
USING (
  bucket_id = 'payment-proofs'
);

-- ------------------------------------------------------------
-- 4. NEWSLETTERS
-- ------------------------------------------------------------
-- Admin is the only uploader/editor/deleter. Newsletter downloads continue to
-- work through the public bucket URL, so anon object-list/read policy is not
-- required.

CREATE POLICY newsletters_admin_insert
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'newsletters'
  AND public.is_admin()
);

CREATE POLICY newsletters_admin_select
ON storage.objects
FOR SELECT
TO authenticated
USING (
  bucket_id = 'newsletters'
  AND public.is_admin()
);

CREATE POLICY newsletters_admin_update
ON storage.objects
FOR UPDATE
TO authenticated
USING (
  bucket_id = 'newsletters'
  AND public.is_admin()
)
WITH CHECK (
  bucket_id = 'newsletters'
  AND public.is_admin()
);

CREATE POLICY newsletters_admin_delete
ON storage.objects
FOR DELETE
TO authenticated
USING (
  bucket_id = 'newsletters'
  AND public.is_admin()
);

COMMIT;
